// Selector Utils — 多策略选择器生成（元素选择器与录制器共用）
// 候选按稳定性排序：测试属性 > 语义 id > name/aria > 语义 class > nth-of-type 路径
(function () {
  'use strict';

  if (self.SelectorUtils) return;

  var TEST_ATTRS = ['data-testid', 'data-test', 'data-cy', 'data-qa'];

  function cssEscape(value) {
    return (window.CSS && CSS.escape) ? CSS.escape(value) : String(value).replace(/([^\w-])/g, '\\$1');
  }

  // 识别自动生成的 id/class（构建工具哈希、纯数字、超长随机串）
  function isAutoGeneratedToken(token) {
    if (!token) return true;
    if (/^\d/.test(token)) return true;
    if (/^(css|sc|jss|svelte|chakra|emotion)-/i.test(token)) return true;
    if (/^data-(v|s)-/i.test(token)) return true; // Vue scoped (data-v-xxxx) / Svelte (data-s-xxxx)
    if (/^_ngcontent-/i.test(token)) return true; // Angular
    if (/^__/.test(token)) return true; // BEM private / CSS Modules
    if (/^_.+_/.test(token)) return true;
    if (/[0-9a-f]{5,}/i.test(token) && /\d/.test(token)) return true;
    if (token.length > 24) return true;
    return false;
  }

  function isUnique(doc, selector) {
    try { return doc.querySelectorAll(selector).length === 1; } catch (_) { return false; }
  }

  function attrSelector(attr, value) {
    return '[' + attr + '="' + String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"]';
  }

  // 从最近的稳定锚点（测试属性/语义 id）向下构建 nth-of-type 路径
  function buildPath(el) {
    var parts = [];
    var cur = el;
    var depth = 0;
    while (cur && cur.nodeType === 1 && depth < 8) {
      var tag = cur.tagName.toLowerCase();
      if (tag === 'html' || tag === 'body') {
        parts.unshift(tag);
        break;
      }
      var anchor = null;
      // 排除框架生成的属性作为锚点（data-v-xxxx, data-s-xxxx, _ngcontent-xxx）
      var hasBuildAttr = false;
      for (var a = 0; a < cur.attributes.length; a++) {
        var an = cur.attributes[a].name;
        if (/^data-(v|s)-/i.test(an) || /^_ngcontent-/i.test(an)) { hasBuildAttr = true; break; }
      }
      if (!hasBuildAttr) {
        for (var i = 0; i < TEST_ATTRS.length; i++) {
          var av = cur.getAttribute(TEST_ATTRS[i]);
          if (av) { anchor = attrSelector(TEST_ATTRS[i], av); break; }
        }
        if (!anchor && cur.id && !isAutoGeneratedToken(cur.id)) anchor = '#' + cssEscape(cur.id);
      }
      if (anchor) {
        parts.unshift(anchor);
        break;
      }
      var index = 1;
      var sib = cur;
      while ((sib = sib.previousElementSibling)) {
        if (sib.tagName === cur.tagName) index++;
      }
      parts.unshift(tag + ':nth-of-type(' + index + ')');
      cur = cur.parentElement;
      depth++;
    }
    return parts.join(' > ');
  }

  function semanticClasses(el) {
    var raw = (typeof el.className === 'string') ? el.className : '';
    return raw.split(/\s+/).filter(Boolean).filter(function (c) {
      return !isAutoGeneratedToken(c) && !/^(hover|active|focus|selected|open|show)/.test(c);
    }).slice(0, 3);
  }

  // 返回候选数组: [{ selector, unique, strategy }]
  function buildCandidates(el) {
    var doc = el.ownerDocument || document;
    var tag = el.tagName.toLowerCase();
    var out = [];

    function push(selector, strategy) {
      if (!selector) return;
      for (var i = 0; i < out.length; i++) {
        if (out[i].selector === selector) return;
      }
      out.push({ selector: selector, unique: isUnique(doc, selector), strategy: strategy });
    }

    for (var i = 0; i < TEST_ATTRS.length; i++) {
      var tv = el.getAttribute(TEST_ATTRS[i]);
      if (tv) push(attrSelector(TEST_ATTRS[i], tv), 'test-attr');
    }

    if (el.id && !isAutoGeneratedToken(el.id)) push('#' + cssEscape(el.id), 'id');

    var formAttrs = ['name', 'aria-label', 'placeholder'];
    for (var j = 0; j < formAttrs.length; j++) {
      var fv = el.getAttribute(formAttrs[j]);
      if (fv) push(tag + attrSelector(formAttrs[j], fv), 'attr');
    }

    // role 属性（如 button[role="tab"]），对 ARIA 组件常用
    var role = el.getAttribute('role');
    if (role) push(tag + attrSelector('role', role), 'role');

    var classes = semanticClasses(el);
    if (classes.length) push(tag + '.' + classes.map(cssEscape).join('.'), 'class');

    push(buildPath(el), 'path');

    return out;
  }

  // 最优单选择器：第一个唯一命中的候选，否则第一个候选
  function bestSelector(el) {
    var candidates = buildCandidates(el);
    for (var i = 0; i < candidates.length; i++) {
      if (candidates[i].unique) return candidates[i].selector;
    }
    return candidates.length ? candidates[0].selector : el.tagName.toLowerCase();
  }

  // 备选链："最优 || 次优"（运行时从左到右降级），最多 chain 2 条
  function buildChain(el) {
    var candidates = buildCandidates(el);
    var unique = candidates.filter(function (c) { return c.unique; });
    var picked = unique.slice(0, 2);
    if (!picked.length) picked = candidates.slice(0, 1);
    return picked.map(function (c) { return c.selector; }).join(' || ');
  }

  self.SelectorUtils = {
    buildCandidates: buildCandidates,
    bestSelector: bestSelector,
    buildChain: buildChain,
  };
})();
